name: Gold Score Test

on:
  workflow_dispatch:

jobs:
  test-score:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run score test
        run: python score_test.py
